improve packaging

diff --git a/contrib/debpkg/aquachain.postinst b/contrib/debpkg/aquachain.postinst
--- a/contrib/debpkg/aquachain.postinst
+++ b/contrib/debpkg/aquachain.postinst
@@ -1,13 +1,16 @@
 #!/bin/sh
 # this is a postinst script for aquachain debian package
-set -e
+# we make systemd unit, user, group, and config files
+set -ex
+now=$(date)
+default_aqua_homedir=/var/lib/aquachain
 
 echo args: $@
 # Source the configuration values.
 if [ -f /etc/aquachain/aquachain.conf ]; then
     . /etc/aquachain/aquachain.conf
 else
-    echo "Configuration file not found."
+    echo "Configuration file not found: /etc/aquachain/aquachain.conf"
     exit 1
 fi
 
@@ -19,91 +22,32 @@ echo "Verbosity: $VERBOSITY"
 echo "Additional Arguments: $AQUACHAIN_ARGS"
 echo "RPC Enabled: $RPC"
 
-
-now=$(date)
-default_aqua_homedir=/var/lib/aquachain
-exit 0
-if ! which systemctl >/dev/null; then
-    echo "warn: systemd not found, skipping aquachain.service installation"
-    exit 0
-fi
-# add user and group
-if ! getent group aqua >/dev/null; then
-    addgroup --system aqua
-    echo "created group: aqua"
-fi
-if ! getent passwd aqua >/dev/null; then
-    adduser --system --ingroup aqua --home "$default_aqua_homedir" --shell /usr/sbin/nologin aqua
-    echo "created user: aqua"
-fi
-RET=
-db_input high aquachain/aquabase || true
-db_go || true
-db_get aquachain/aquabase || true
-aquabase=$RET
-if [ -z "$aquabase" ]; then
-    aquabase=0xDA7064FB41A2a599275Dd74113787A7aA8ee3E4f
+mayberpc=""
+if [ "$RPC" = "1" ]; then
+    mayberpc="-rpc -ws --rpccorsdomain='*' --rpcvhosts='*' -wsorigins '*'"
 fi
 
-db_input high aquachain/datadir || true
-db_go || true
-db_get aquachain/datadir || true
-datadir=$RET
-if [ -z "$datadir" ]; then
-    datadir=${default_aqua_homedir}
-fi
-
-db_input high aquachain/chain || true
-db_go || true
-db_get aquachain/chain || true
-chain=$RET
-if [ -z "$chain" ]; then
-    chain=aqua
-fi
-mayberpc=
-db_input high aquachain/rpc || true
-db_go || true
-db_get aquachain/rpc || true
-rpc=$RET
-if [ -z "$rpc" ]; then
-    rpc=1
-fi
-if [ "$rpc" -eq 1 ]; then
-    mayberpc="-rpc -ws"
-fi
-aqua_args=
-db_input high aquachain/args || true
-db_go || true
-db_get aquachain/args || true
-aqua_args=$RET
-
-db_input medium aquachain/verbosity || true
-db_go || true
-db_get aquachain/verbosity || true
-verbosity=$RET
-if [ -z "$verbosity" ]; then
-    verbosity=4
-fi
 
 if [ ! -d $default_aqua_homedir ]; then
-    echo "warn: aqua homedir not found, creating"
+    echo "aqua homedir not found, creating it: $default_aqua_homedir"
     mkdir -v -p $default_aqua_homedir
     chown -v -R aqua:aqua $default_aqua_homedir
     chmod -v 700 $default_aqua_homedir
     echo "created aqua directory: $default_aqua_homedir"
 fi
 
-mkdir -p /etc/default
+# rare
+if [ -d /etc/default ]; then
+    mkdir -p /etc/default
+fi
+
+# create system env file
 cat >/etc/default/aquachain <<EOF2
 # aquachain config (generated at ${now})
-OPTIONS=-debug ${mayberpc} -jsonlog -chain ${chain} -datadir ${datadir} -verbosity ${verbosity} -aquabase ${aquabase} ${aqua_args}
+# this env file is used by the systemd service
 JSONLOG=0
 NO_SIGN=1
 NO_KEYS=1
-# unsafe stuff for testing/example
-#UNSAFE_RPC_ALLOW_IP=1
-# example allow all rpc and ws connections
-#OPTIONS=-nokeys -chain testnet -allowip 0.0.0.0/0 --txpool.nolocals -aquabase ${aquabase} -rpc -ws -debug -verbosity 4 --rpccorsdomain='*' --rpcvhosts='*' -wsorigins '*'
 EOF2
 chmod -v 600 $tmpdir/etc/default/aquachain
 
